frex/frex/urls.py
"""frex URL Configuration """
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #..........START..........
    path('accounts/', include('django.contrib.auth.urls')),
    #.........END..............

    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('profile/', include('profille.urls', namespace='profille')),
    path('html/', include('post.urls', namespace='post')),
    path('django/', include('post1.urls', namespace='post1')),
    path('css/', include('post2.urls', namespace='post2')),
    path('python/', include('post3.urls', namespace='post3')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frex/home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as v_iews
app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('login/', v_iews.LoginView.as_view(), name='login'),
]

frex/profille/urls.py
from django.urls import path
from . import views

app_name = 'profille'
urlpatterns = [
    path('<slug>/', views.profile, name='profile'),
    path('<slug>/edit', views.edit_profile, name='edit_profile'),
]

frex/templates/profile/edit_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}

{% block content %}
<div class='container'>
   <h4 class="bg-light text-center text-primary">Edit your profile {{ user }}</h4>
    <form method="post" enctype="multipart/form-data">

    {% csrf_token %}
    {% bootstrap_form profile_form %}
    {% bootstrap_form user_form %}

<button class='btn btn-block btn-success' type="submit">Save</button>
</form>
</div>
{% endblock %}

frex/templates/profile/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>
  .icone {
    width: 110px;
    height: 110px;
    border-radius: 50%;
  }
</style>

  <center>
    <br>
{% if user == profile.user %}
<a style="margin-right: 60%;" class="btn my-2 my-sm-0 btn-outline-success" href="{% url 'profille:edit_profile' profile.slug %}">
   Edit Profile <img class="navbar-toggler-icone" src="{% static 'img/icon-addlink.svg' %}">
 </a>
{% endif %}
{% if not profile.image %}
   <img class="card im_age" src="{% static 'images/1.jpg' %}">
{% else %}
<img class="card icone" src="{{ profile.image.url }}">
<br>
{% endif %}
<h4 class="text-dark">{{ profile.user }}</h4>
<small class="text-center text-info">i'm {{ profile.user.first_name }} {{ profile.user.last_name }}</small>
<p class="text-primary">{{ profile.user.email }}</p>
  </center>
  
<div class="container">
  <div class="card bg-light">
  <h1 class="text-center lead text-dark">
    {{ profile.headline }}
  </h1></div>
  <div>
  <br>
 <div class="alert alert-info alert-dismissable">
   <p class="text-dark lead">
   {{ profile.bio | escape | linebreaks }}
   </p>
  </div>
  </div>
</div>
 
{% if user == profile.user %}

<div class="container">
  <button type="button" data-toggle="modal" data-target="#myModal" class="btn-block btn-outline-info text-success lead">Account security</button>
  <div id="myModal" class="modal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h3 class="modal-title">Account security</h3>
          <button data-dismiss="modal" class="btn-danger">X</button>
        </div>
        <div class="modal-body">
       <a class="text-center text-danger card nav-link" href="{% url 'password_change' %}">Change Password</a>
      </div>
        <div class="modal-body">
      <a class="text-center card nav-link text-danger" href="{% url 'password_reset' %}">Forget Password</a>
       </div>
      </div>
    </div>
  </div>
</div> 
<br>
 <center> <a class="btn my-2 my-sm-0 btn-outline-danger" href="{% url 'logout' %}">
  Logout <img class="navbar-toggler-icone" src="{% static 'img/icon-no.svg' %}">
 </a></center>
{% else %}

<a href="/" class="btn btn-block my-2 my-sm-0 btn-outline-primary">Home</a>
<a href="#"class="btn btn-block my-2 my-sm-0 btn-outline-primary">About us</a>

{% endif %}
{% if user.is_authenticated %}

{% else %}
<br>
<div class="container">
<center>
<p>Sign UP now to add your profile<p>
  <a class="btn btn-block my-2 my-sm-0 btn-outline-primary" href="{% url 'login' %}">Login</a>
  <a class="btn btn-block my-2 my-sm-0 btn-outline-primary" href="{% url 'home:signup' %}">Sign UP</a>
</center>
</div>
{% endif %}

{% endblock %}