frex/frex/urls.py
"""frex URL Configuration """
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #..........START..........
    path('accounts/', include('django.contrib.auth.urls')),
    #.........END..............

    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('profile/', include('profille.urls', namespace='profille')),
    path('html/', include('post.urls', namespace='post')),
    path('django/', include('post1.urls', namespace='post1')),
    path('css/', include('post2.urls', namespace='post2')),
    path('python/', include('post3.urls', namespace='post3')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frex/post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('', views.post, name='post'),
    path('<id>/', views.detail, name='detail'),
]

frex/post1/urls.py
from django.urls import path
from . import views

app_name = 'post1'

urlpatterns = [
    path('', views.post, name='post1'),
    path('<id>/', views.detail, name='detail1'),
]

frex/post/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    image = models.FileField(upload_to='images/')
    content1 = models.TextField(default=' ')
    code1 = models.TextField(default=' ')
    content2 = models.TextField(default=' ')
    code2 = models.TextField(default=' ')
    video = models.FileField(upload_to='video/')
    time = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.title

class Coment(models.Model):
    name = models.ForeignKey(Post, on_delete=models.CASCADE)
    coment = models.CharField(max_length=500)
    time = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.coment

frex/post1/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Post1(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    image = models.FileField(upload_to='images/')
    content1 = models.TextField(default=' ')
    code1 = models.TextField(default=' ')
    content2 = models.TextField(default=' ')
    code2 = models.TextField(default=' ')
    video = models.FileField(upload_to='video/')
    time = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.title
class Coment1(models.Model):
    name = models.ForeignKey(Post1, on_delete=models.CASCADE)
    coment = models.CharField(max_length=500)
    time = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.coment

frex/post/forms.py
from django import forms
from .models import Coment

class ComentForm(forms.ModelForm):
    class Meta:
        model = Coment
        fields = ['coment']

frex/post1/forms.py
from django import forms
from .models import Coment1

class ComentForm(forms.ModelForm):
    class Meta:
        model = Coment1
        fields = ['coment']

frex/post/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Coment
from .forms import ComentForm
from profille.models import Profile
def add_coment(request):
    if request.method == 'POST':
        form = ComentForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = ComentForm()
    context = {
        'form': form,
    }
    return render(request, 'post/detail.html', context)

def post(request):
    all_post = Post.objects.all()
    context = {
        'all_post': all_post,
    }
    return render(request, 'post/post.html', context)

def detail(request, id):
    post = get_object_or_404(Post, id=id)
    all_coment = Coment.objects.all()
    var = len(all_coment)
    profile = Profile.objects.all()
    context = {
        'profile': profile,
        'post': post,
        'var': var,
        'all_coment': all_coment,
    }
    return render(request, 'post/detail.html', context)

frex/post1/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from .models import Post1, Coment1


def post(request):
    all_post = Post1.objects.all()
    context = {
        'all_post': all_post,
    }
    return render(request, 'post1/post.html', context)

def detail(request, id):
    post = get_object_or_404(Post1, id=id)
    all_coment = Coment1.objects.all()
    var = len(all_coment)
    context = {
        'post': post,
        'var': var,
        'all_coment': all_coment,
    }
    return render(request, 'post1/detail.html', context)

frex/templates/post1/detail.html
{% extends 'base.html' %}
{% block content %}
  <br>
<div class="container card">
  <h1 class="text-center text-info">{{ post.title }}</h1>
  <br>
  <center>
  <img src="{{ post.image.url }}" class="img-thumbnail" height="100px"/>
  </center>
  <br>
  <div class="container">
       <p class="lead text-muted">{{ post.content1 | escape | linebreaks }}</p>
       <br>Example code:
       <div class="alert alert-secondary" style="border-left: 2px solid red">
       <code class="highlighter-rouge language-html" data-lang="html">
         {{ post.code1 | escape | linebreaks }}
       </code>
       </div>
  </div>
  
    <div class="">
      <p class="lead text-muted">{{ post.content2 | escape | linebreaks }}</p>
      <br>Example code:
      <div class="alert alert-secondary" style="border-left: 2px solid red">
        <code class="highlighter-rouge language-html" data-lang="html">
          {{ post.code2 | escape | linebreaks }}
        </code>
      </div>
    </div>
    <video controls src="{{ post.video.url }}"></video>
    <br>
    <small style="margin-top: 19px;">created: {{ post.time }}</small>


{% if all_coment %}
 <main role="main" class="container">
    <div class="my-3 p-3 bg-white rounded shadow-sm">
   <h6 class="border-bottom border-gray pb-2 mb-0">Coments {{ var }}</h6>
  {% for coment in all_coment %}                
    <div class="media text-muted pt-3">
    <img src="{{ user.profile.image.url }}" class="bd-placeholder-imgmr-2 rounded" width="42" height="42" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32">
    <rect width="100%" height="100%" fill="#007bff" />
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          <strong class="d-block text-primary">{{ user.username }}</strong>
          {{ coment.coment }}
         <br>
          <small>{{ coment.time }}</small>
        </p>
    </div>
  {% endfor %}
    </div>
  </main>
{% else %}                
  <br>
 <h6 class="border-bottom border-gray pb-2 mb-0">No coments Now</h6>
{% endif %}


{% endblock %}

frex/templates/post1/post.html
{% extends 'base.html' %}
{% block content %}
{% if all_post %}
  <h3 class="text-center text-info">All post</h3>
     {% for post in all_post %}
          <br>
          <div class="col-md-12">
            <div class="card mb-4 shadow-sm">
                 <title>{% block title %}{% endblock %}</title>
                    <rect width="100%" height="100%" fill="#55595c" />
                      <div class="card-body">
                      <p class="text-dark lead">{{ post.user }}</p>
                 <h4 class="text-danger text-penter mb-3">{{ post.title }}</h4>
                    <img class="img4" src="{{ post.image.url }}">
                      <p class="card-text">{{ post.content1 | truncatewords:7 }}</p>
                <div class="d-flex justify-content-between align-items-center&&">
                  <div class="btn-group">
                     <a href="{% url 'post1:detail1' id=post.id %}" class="btn btn-outline-success btn-sm" >Learn More</a>
                  </div>
                  <small class="text-muted">{{ post.time }}</small>
                 </div>
               </div>
              </div>
            </div>
           </main>
     {% endfor %}
   {% else %}
     <p class="text-center">No Post Available Now please try again ...</p>
   {% endif %}
{% endblock %}